# Generated by Django 6.0 on 2025-12-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_payment_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="unit_amount",
        ),
    ]
