# Generated by Django 5.2.9 on 2025-12-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_amount_payment_unit_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
