# Generated by Django 6.0 on 2025-12-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": (),
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
    ]
