# Generated by Django 6.0 on 2025-12-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "урок", "verbose_name_plural": "уроки"},
        ),
    ]
